version: '3'

services:
  haproxy:
    build: ./haproxy
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"

  portainer:
    image: "portainer/portainer"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal

volumes:
  portainer_data:

networks:
  internal: